# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='fooditems',
            name='r_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_management.Restaurant'),
        ),
    ]
