# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditems',
            old_name='r_id',
            new_name='f_id',
        ),
    ]
