# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_management', '0002_auto_20170324_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
