# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
            ],
        ),
    ]
