# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_management', '0002_auto_20170325_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('1', 'pending'), ('0', 'closed')], max_length=50),
        ),
    ]
