# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 07:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_name', models.CharField(blank=True, max_length=500, null=True)),
                ('order_items', models.CharField(blank=True, max_length=5000, null=True)),
                ('status', models.CharField(max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('extra_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('delivery_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('restaurant_id', models.CharField(max_length=1000)),
                ('delivery_address', models.CharField(blank=True, max_length=2000, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('order_type', models.CharField(max_length=10)),
                ('bill_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_update_by', models.CharField(max_length=100)),
                ('last_update_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
