# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 19:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user_type',
            field=models.CharField(default='customer', max_length=100),
        ),
    ]
