# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20170408_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='user_type',
            field=models.CharField(choices=[('c', 'customer'), ('s', 'staff')], default='customer', max_length=100),
        ),
    ]
