# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('manager', 'Manager'), ('attendant', 'Attendant'), ('delivery_boy', 'Delivery Boy'), ('chef', 'Chef')], default=('customer', 'Customer'), max_length=30)),
                ('user_email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('user_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user_name', models.CharField(default='User Name', max_length=50)),
                ('activation_key', models.CharField(max_length=257)),
                ('key_expires', models.DateTimeField()),
                ('acc_status', models.CharField(choices=[('active', 'Active'), ('verified', 'Verified')], default=('active', 'Active'), max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
