# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='acc_status',
            field=models.CharField(choices=[('active', 'Active'), ('verified', 'Verified'), ('blacklisted', 'Blacklisted')], default=('active', 'Active'), max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
