# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-12 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
