# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 10:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_name', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('extra_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_charges', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer_id', models.CharField(max_length=100)),
                ('restaurant_id', models.CharField(max_length=1000)),
                ('delivery_address', models.CharField(max_length=2000)),
                ('payment_type', models.CharField(max_length=50)),
                ('order_type', models.CharField(max_length=10)),
                ('bill_date', models.DateTimeField(blank=True)),
                ('delivery_by', models.CharField(max_length=100)),
                ('last_update_by', models.CharField(max_length=100)),
                ('last_update_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
