# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
