# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20170326_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.CharField(max_length=5000),
        ),
    ]
